---
- name: Install dependencies
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch APT Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT Repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ auditbeat_major_version }}.x/apt stable main'
    filename: elastic
    state: present
    update_cache: true

- name: Install Auditbeat
  apt:
    name: auditbeat
    state: present
  notify: Restart Auditbeat
